version: '3.9'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: calorie_tracker_db
      POSTGRES_USER: calorie_user
      POSTGRES_PASSWORD: calorie_password
    networks:
      - app_network

  web:
    build: .
    command: python tracker/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DATABASE_URL: postgres://calorie_user:calorie_password@db:5432/calorie_tracker_db
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
